name: GitHub - Activity - Readme

on:
  # schedule:
  #   - cron: "0 21 * * *"

  schedule:
    # Runs every 30 minutes
    - cron: "*/30 * * * *"
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: DenverCoderOne/github-activity-readme@commit-username-and-email
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
